Add Gamecontroller.php, game.css, folder Game and it view game.html.twig
WildCodeSchool/tours-php-2103-project2-stercket pull request #4
Opened 2021-04-14 12:16 UTC by StephaneSauvaget

2021-04-14 13:51 UTC, Orijma commented
Different indentation than my home.html.twig
Don't know which one Romain prefer
we'll see this soon

2021-04-14 13:52 UTC, Orijma approved these changes

2021-04-16 06:54 UTC, RomainClair requested changes
You probably should name you branches and PR according to what you want to do, and not a list of files.
Probably something like : the main game page - first draft

2021-04-16 06:54 UTC, RomainClair commented on src/Controller/GameController.php
> + */
Seems false. Beware of copy/paste =)

2021-04-16 06:54 UTC, RomainClair commented on src/View/Game/game.html.twig
> +            <link href="https://fonts.googleapis.com/css2?family=Passero+One&display=swap" rel="stylesheet">
It's probably better to have self hosted fonts

2021-04-16 06:54 UTC, RomainClair commented on src/View/Game/game.html.twig
> +                <img src="" alt="">
Seems useless... and probably not valid

2021-04-16 06:54 UTC, RomainClair commented on src/View/Game/game.html.twig
> +                <button class = "button buttonBattle"> Battle </button>
Do you plan to have JS involved ?
If not this should probably be links or forms ot have a client/server interaction
And use CSS if you want them to looks like buttons

2021-04-16 08:15 UTC, closed without merging