Database creation
WildCodeSchool/tours-php-2103-project2-stercket pull request #5
Opened 2021-04-14 12:27 UTC by AmanelGau

2021-04-14 12:28 UTC, Orijma submitted a review, later dismissed

2021-04-14 12:38 UTC, RomainClair requested changes
Now, we have a previous .sql file. So there's two possible case :

    Those who don't have a previous database : for those no problem
    Those who already imported the previous sql file. For those the new version will be invalid because it'll try to create an already existing table.
    May be take a look at the DROP TABLE IF EXISTS sql statements

2021-04-14 12:49 UTC, Orijma approved these changes

2021-04-14 13:16 UTC, StephaneSauvaget approved these changes

2021-04-15 12:53 UTC, RomainClair approved these changes
It was probably not usefull to modifiy the simple-mvc.sql file because it will probably don't last long in you repo.

2021-04-15 12:53 UTC, merged